export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const INCREMENT_IF_EVEN = "INCREMENT_IF_EVEN";
export const INCREMENT_IF_ODD = "INCREMENT_IF_ODD";
export const INCREMENT_ASYNC = "INCREMENT_ASYNC";
